---
title: "Introduction"
author: "Mauricio Tec & Natalia Zuniga"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

We'll show how to use the package in a static form (no dynamic component).

Here's some fake data.

```{r}
set.seed(999999)
library(mvtnorm)
library(pldensity)
```

```{r}
d <- 2
n <- 300
w_true <- c(0.3, 0.1, 0.21)
mu_true <- matrix(c(-2, 2, 0, -2, 1.5, 0), ncol = 2, byrow = TRUE)
sigma2_true <- 0.35
simdata <- matrix(0, n, d)
simdata[1:100, ] <- rmvnorm(100, mu_true[1, ], diag(sigma2_true, d))
simdata[101:200, ] <- rmvnorm(100, mu_true[2, ], 0.5 * diag(sigma2_true, d))
simdata[201:300, ] <- rmvnorm(100, mu_true[3, ], diag(sigma2_true, d))
ground_truth <- c(rep(1, 100), rep(2, 100), rep(3, 100))
```

```{r, fig.width=5, fig.height=4}
plot(simdata, pch = 21, bg = ground_truth, main = "simulated bidimensional data")
```


```{r}
nparticles = 500
mod0 <- ddpn_init(
  nparticles = nparticles, 
  lambda = c(0, 0), 
  kappa = 1,
  nu = 3,
  Omega = diag(2),
  alpha = 2,
  rho = 0.9)
```


```{r}
res <- ddpn_mix(mod0, simdata[base::sample(300), ])
```

```{r}
resol <- 50
x = seq(-5, 5, length.out = resol)
y = seq(-5, 5, length.out = resol)
grid <- data.matrix(expand.grid(x, y))
dens <- ddpn_eval(res$updated_model, grid, nparticles = nparticles)
```

```{r}
z <- matrix(dens, ncol = resol)
```

```{r, fig.width=5, fig.height=4}
filled.contour(x = x, y = y, z = log(z), nlevels = 20, main = "logdensity")
```

```{r, fig.width=5, fig.height=4}
contour(x = x, y = y, z = log(z), nlevels = 10, main = "density fit")
points(simdata, pch = 21, bg = ground_truth)
```

```{r}
sum(dens) * (x[2] - x[1]) * (y[2] - y[1])
```

```{r}
res$marginal_loglikelihood
```

```{r, fig.width=5, fig.height=3}
plot(res$sequential_likelihood, type = "l", ylim = c(0, .5))
```

