# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title test dynamic particle io
#' @export
iotest_dynamic_particle <- function(L) {
    .Call('_pldensity_iotest_dynamic_particle', PACKAGE = 'pldensity', L)
}

#' @title test hyperparam
#' @export
iotest_ddpn_hyperparam <- function(L) {
    .Call('_pldensity_iotest_ddpn_hyperparam', PACKAGE = 'pldensity', L)
}

#' @title test ddpn I/O
#' @export
iotest_ddpn <- function(L) {
    .Call('_pldensity_iotest_ddpn', PACKAGE = 'pldensity', L)
}

#' @title Model initialisation
#' @export
dpn_init <- function(nparticles, alpha, lambda, kappa, nu, Omega) {
    .Call('_pldensity_dpn_init', PACKAGE = 'pldensity', nparticles, alpha, lambda, kappa, nu, Omega)
}

#' @title Dirichlet Process Normal Mixture Kernel Density Estimation
#' @export
dpn_mix <- function(model, x, epochs = 1L) {
    .Call('_pldensity_dpn_mix', PACKAGE = 'pldensity', model, x, epochs)
}

#' @title Eval Point Density
#' @export
dpn_eval <- function(model, xnew, nparticles = 50L) {
    .Call('_pldensity_dpn_eval', PACKAGE = 'pldensity', model, xnew, nparticles)
}

#' @title Take marginals
#' @export
dpn_marginal <- function(model, dims) {
    .Call('_pldensity_dpn_marginal', PACKAGE = 'pldensity', model, dims)
}

#' @title Eval Point Conditional density
#' @export
dpn_conditional <- function(model, xnew, eval_dims, condition_dims, condition_values, nparticles = 50L) {
    .Call('_pldensity_dpn_conditional', PACKAGE = 'pldensity', model, xnew, eval_dims, condition_dims, condition_values, nparticles)
}

